<?php

namespace ignatenkovnikita\swagger;


use yii\base\InvalidConfigException;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * Class Module
 * @package ignatenkovnikita\swagger
 */
class Module extends \yii\base\Module
{

    /**
     * @var string
     */
    public $path;

    /**
     * @var string
     */
    public $url;


    /**
     * @var \Closure
     */
    public $beforeParsing;
    /**
     * Call function
     * @var \Closure
     */
    public $afterRender;


    /**
     * @var \Closure
     */
    public $isDisable;


    /**
     * @var string
     */
    public $controllerNamespace = 'ignatenkovnikita\swagger\controllers';

    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        if ($this->isDisable()) {
            throw new HttpException(404);
        }

        if (empty($this->path) && empty($this->url)) {
            throw  new InvalidConfigException('Scan dir not empty or url not empty');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function isDisable()
    {
        if (is_callable($this->isDisable)) {
          return  call_user_func($this->isDisable);
        }
    }







}