<?php
namespace ignatenkovnikita\swagger;


use yii\base\InvalidConfigException;

/**
 * Class Module
 * @package ignatenkovnikita\swagger
 */
class Module extends \yii\base\Module
{

    /**
     * @var string
     */
    public $path;

    /**
     * @var string
     */
    public $url;


    /**
     * @var string
     */
    public $controllerNamespace = 'ignatenkovnikita\swagger\controllers';

    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        if (empty($this->path) && empty($this->url)) {
            throw  new InvalidConfigException('Scan dir not empty or url not empty');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }


}